In [1]:
import numpy as np



In [2]:
a=np.array([1,2,3]),dtype='int32')
print(a)

[1 2 3]


In [3]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# get the dimension
a.ndim

1

In [5]:
# get shape
b.shape


(2, 3)

In [6]:
# get type
a.dtype

dtype('int32')

In [7]:
# get size
a.itemsize

4

In [8]:
# get size
a.itemsize

4