In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import numpy as np

digits=load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\asus\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [4]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)


0.9833333333333333

In [5]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9481481481481482

In [6]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=10)
kf

KFold(n_splits=10, random_state=None, shuffle=False)

In [7]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9,10]):
    print(train_index,test_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [10]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [11]:
get_score((LogisticRegression()),X_train,X_test,y_train,y_test)

C:\Users\asus\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [13]:
get_score((SVC()),X_train,X_test,y_train,y_test)

0.9833333333333333

In [17]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [27]:
scores_1=[]
score_svm=[]
scores_rf=[]

for train_index, test_index in kf.split(digits.data):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]
    
    
print(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))  
print(get_score(SVC(),X_train,X_test,y_train,y_test))    
print(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))    

C:\Users\asus\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9610027855153204
0.9944289693593314
0.9832869080779945


In [21]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
from sklearn.metrics import accuracy_score

# Load digits dataset
digits = load_digits()

# Initialize KFold
kf = KFold(n_splits=5, shuffle=True)

scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]

    # Define and fit models
    lr = LogisticRegression()
    svm = SVC()
    rf = RandomForestClassifier()

    lr.fit(X_train, y_train)
    svm.fit(X_train, y_train)
    rf.fit(X_train, y_train)

    # Predict and calculate scores
    lr_score = lr.score(X_test, y_test)
    svm_score = svm.score(X_test, y_test)
    rf_score = rf.score(X_test, y_test)

    scores_lr.append(lr_score)
    scores_svm.append(svm_score)
    scores_rf.append(rf_score)

print("Logistic Regression Scores:", scores_lr)
print("SVM Scores:", scores_svm)
print("Random Forest Scores:", scores_rf)


C:\Users\asus\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\asus\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

Logistic Regression Scores: [0.9694444444444444, 0.9666666666666667, 0.9693593314763231, 0.9637883008356546, 0.958217270194986]
SVM Scores: [0.9888888888888889, 0.9916666666666667, 0.9944289693593314, 0.9888579387186629, 0.9805013927576601]
Random Forest Scores: [0.9833333333333333, 0.9722222222222222, 0.9832869080779945, 0.9860724233983287, 0.9693593314763231]


In [34]:
scores_1=[]
score_svm=[]
scores_rf=[]

for train_index, test_index in kf.split(digits.data):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]
    
    
scores_1.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))  
scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))    
scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))    

C:\Users\asus\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [35]:
scores_1

[0.9610027855153204]

In [36]:
scores_svm

[0.9888888888888889,
 0.9916666666666667,
 0.9944289693593314,
 0.9888579387186629,
 0.9805013927576601,
 0.9805013927576601,
 0.9860724233983287,
 0.9805013927576601]

In [37]:
scores_rf

[0.9777158774373259]

In [38]:
from sklearn.model_selection import cross_val_score

In [39]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\asus\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\asus\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [40]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [41]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.92222222, 0.89444444, 0.95821727, 0.96935933, 0.91364903])

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)

array([0.85      , 0.78055556, 0.88579387, 0.88022284, 0.83008357])

In [44]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.92222222, 0.89722222, 0.96100279, 0.95543175, 0.91364903])