In [2]:
import numpy as np

In [3]:
import sys

# basics

In [5]:
a=np.array([1,2,3],dtype='int32')

In [7]:
b=np.array([[4.0,5.0,6.0],[7.0,8.0,9.0]])
print(b)

[[4. 5. 6.]
 [7. 8. 9.]]


# get dimension


In [10]:
a.ndim
b.ndim

2

In [11]:
# get shape
b.shape

(2, 3)

In [12]:
# get type
a.dtype


dtype('int32')

In [15]:

# get size

b.itemsize

8

In [16]:
# get total size
a.nbytes

12

# acess change  specific elements ,row

In [18]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
# get a specific element[r,c]
a[1,-4]
a[0,5]

6

In [22]:
# get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [23]:
# get a specific column
a[:,1]

array([2, 9])

In [24]:
# get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [25]:
#getting a little more fancy
# [startingindex:endindex:stepsize]
a[0,1:4:1]

array([2, 3, 4])

In [27]:
# changing element of array
a[1,5]=20
print(a)

a[:,2]=[1,2]
print(a)


[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [28]:
# 3d example
b=([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


In [30]:
# 3d example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# get specific element (work outside in)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [32]:
# get specific element (work outside in)
b[0,:,1]

array([2, 4])

In [33]:
# get specific element (work outside in)
b[1,1,:]

array([7, 8])

In [34]:
# replace
b[:,1,:]=[[9,9],[8,8]]

In [35]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [36]:
# INTIALZING DIFFERENT TYPES OF ARRAYS
# all 0's matrix
np.zeros((2,3))

np.zeros((2,2,3,4))


array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [37]:
# all 1;s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [38]:
# any other number
np.full((2,2),99.0)

array([[99., 99.],
       [99., 99.]])

In [40]:
# any other full_like method
# reusing the shape
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [42]:
# Ramdom decimal numbers
np.random.rand(4,2,2)

np.random.random_sample(a.shape)

array([[0.76687101, 0.67720601, 0.94721737, 0.0772717 , 0.76026255,
        0.32920141, 0.37471499],
       [0.20473653, 0.56197056, 0.65720447, 0.83032219, 0.25487323,
        0.91697031, 0.18548909]])

In [43]:
# random integer values
np.random.randint(4,7,size=(3,3))

array([[6, 4, 6],
       [4, 4, 5],
       [6, 4, 4]])

In [44]:
# the identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
# repeat an array
arr=np.array([1,2,3])
r1=np.repeat(arr,3,axis=0)
print(r1)

arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [46]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!!!!!!

In [47]:
a=np.array([1,2,3])
b=a.copy()
c=b
b[0]=100
print(a)
print(b)
print(c)

[1 2 3]
[100   2   3]
[100   2   3]


#####mathematics
a=np.array([1,2,3,4])
print(a)

In [48]:
a=np.array([1,2,3,4]) 
print(a)
a+2

[1 2 3 4]


array([3, 4, 5, 6])

In [49]:
a-2

array([-1,  0,  1,  2])

In [50]:
a*2

array([2, 4, 6, 8])

In [51]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [52]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [53]:
b=np.array([1,8,9,0])
a+b

array([ 2, 10, 12,  4])

In [54]:
a**2

array([ 1,  4,  9, 16])

In [56]:
# take the sign pof all data types
np.cos(a)
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [57]:
## for a lot more(https://docs.scipy.org/doc/numpy/reference/routines.math.html


##### linear algebra

In [44]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [58]:
# find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

In [59]:
# # for a lot more(https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
# deyerminant
# trace
# singular vector decomposition
# eigen values
# matrix name
# inverse
# etc...


#####statics

In [60]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.min(stats,axis=0)

array([1, 2, 3])

In [62]:
np.max(stats,axis=1)

array([3, 6])

In [63]:
np.sum(stats)
np.sum(stats,axis=0)
#np.sum(stats,axis=1)

array([5, 7, 9])

# reorganisazing arrays

In [64]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape(2,2,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# miscellaneous

## low data from file

In [66]:
np.titanictxt('data.txt',delimeter=',')

AttributeError: module 'numpy' has no attribute 'titanictxt'